env:
  TASKS_TO_SKIP: ".*"
skip: $CIRRUS_TASK_NAME =~ $TASKS_TO_SKIP

linux_task:
  container:
    image: ubuntu:latest
  script:
    - echo hello

windows_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
  script:
    - echo hello
