env:
  TASKS_TO_RUN: ".*"
  TASKS_TO_SKIP: "linux"
only_if: $CIRRUS_TASK_NAME =~ $TASKS_TO_RUN
skip: $CIRRUS_TASK_NAME =~ $TASKS_TO_SKIP

linux_task:
  container:
    image: ubuntu:latest
  script:
    - echo hello

windows_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
  script:
    - echo hello
