only_if: $CIRRUS_TASK_NAME =~ ''

linux_task:
  container:
    image: ubuntu:latest
  script:
    - echo hello

windows_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
  script:
    - echo hello
